spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
            '[/**]':
              allowedOriginPatterns: # Use allowedOriginPatterns instead of allowedOrigins
                - "http://localhost:4200"  # Example origin
                - "https://your-production-domain.com"  # Add more origins as needed
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders:
                - "*"
              allowCredentials: true
      routes:
        - id: login
          uri: lb://auth-service
          predicates:
            - Path=${api.path}${api.version}/auth/login
          filters:
            - name: LoggingFilter
        - id: refresh-token
          uri: lb://auth-service
          predicates:
            - Path=${api.path}${api.version}/auth/refresh-token
          filters:
            - name: LoggingFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=${api.path}${api.version}/auth/**
          filters:
            - name: LoggingFilter
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=${api.path}${api.version}/documents/**
          filters:
            - name: JwtAuthFilter
              args:
                authValidationUrl: lb://auth-service${api.path}${api.version}/auth/validate
        - id: user-service
          uri: lb://auth-service
          predicates:
            - Path=${api.path}${api.version}/users/**
          filters:
            - name: JwtAuthFilter
              args:
                authValidationUrl: lb://auth-service${api.path}${api.version}/auth/validate
        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=${api.path}${api.version}/locations/**
          filters:
            - name: JwtAuthFilter
              args:
                authValidationUrl: lb://auth-service${api.path}${api.version}/auth/validate
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

api:
  path: /api/
  version: v1

# Server Port
server:
  port: 8080

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG