spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=${api.path}${api.version}/auth/**
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=${api.path}${api.version}/documents/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=${api.path}${api.version}/users/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

api:
  path: /api/
  version: v1

# Server Port
server:
  port: 8080
